name: policyscan
description: "A comprehensive finance and insurance app with AI capabilities."

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.2.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  syncfusion_flutter_charts: ^24.1.40
  flutter_svg: ^2.0.7
  fl_chart: ^0.65.0  # Add this line for the fl_chart package
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fan.png
    - assets/images/fan2.png
    - assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#FFFFFF" # sets background to white
  adaptive_icon_foreground: assets/images/logo.png

#  fonts:
#    - family: Inter
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf
#        - asset: assets/fonts/Inter-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Inter-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Inter-Bold.ttf
#          weight: 700




